[pytest]
# Remove the --update-json option
addopts = 
testpaths = tests
python_files = *test*.py
python_classes = Test*
python_functions = test_*
markers =
    testcase_id: mark a test with a test case ID